### ISSUE TITLE
The confuse thing I want consult you.

### ISSUE THREAD

**Issue by wu-jun-jie** [fafhrd91/netx#1]
hi @fafhrd91 , i 'm sorry to open this issure, but I don't know where to find you and get response.

current I use actix-web, it's cool, I want to create a async pg connect pool for it.  then i find [your work](https://github.com/fafhrd91/rust-postgres/commit/53cbc27d888fd2652101ff8ef9c00e6669dc2b32), you remove 'send, arc, mutex' and it wiil can't be used in Multithread right? so is it also whether need a Multithread connect pool ? I know like nodejs use redis no need Multithread connect pool .

can you Point me? whether there is new way?

**Comment by fafhrd91** [comment]
I made changes specifically for tech empower benchmark. It is not official and I don’t think you should use it. But in general, actix is single threaded, so I’d use pool per thread approach

**Comment by wu-jun-jie** [comment]
thanks.
